/**
 * SEASON 2: NEON APOCALYPSE
 * 100 Levels · Exklusive Belohnungen · Neu & verbessert
 * Start date: 2026-04-01
 *
 * TOKEN-REDESIGN v2: Deflationäres Modell
 * Gesamt-Tokens im Pass: ~23.000 (vorher: ~3.500.000)
 * Ziel: Jeder Token-Drop fühlt sich bedeutsam an.
 */

export const SEASON_2_START = new Date('2026-04-01T00:00:00+02:00');
export const SEASON_2_NAME = 'Neon Apocalypse';
export const SEASON_2_DESCRIPTION = 'Die Welt brennt – schalte exklusive Überlebens-Ausrüstung frei. 100 Level voller einzigartiger Belohnungen.';
export const SEASON_2_PREMIUM_PRICE = 125000;

// ── S2 Ship Skins ──
export const S2_SHIPS = [
  { id: 's2_phantom',   name: 'Phantom Strike',    desc: 'BP S2 Level 5 – Unsichtbar im Schatten',         color: '#374151', glowColor: '#9ca3af', emoji: '👤' },
  { id: 's2_hellfire',  name: 'Hellfire Mk.II',    desc: 'BP S2 Level 40 – Feuerdämon aus der Apokalypse', color: '#dc2626', glowColor: '#f97316', emoji: '🔥' },
  { id: 's2_ghost',     name: 'Ghost Protocol',    desc: 'BP S2 Level 60 – Geist aus einer anderen Zeit',  color: '#e2e8f0', glowColor: '#a5f3fc', emoji: '👻' },
  { id: 's2_titan',     name: 'Apocalypse Titan',  desc: 'BP S2 Level 80 – Das mächtigste Schiff',         color: '#7c3aed', glowColor: '#22d3ee', emoji: '🌌' },
  { id: 's2_apex',      name: 'APEX Predator',     desc: 'BP S2 Level 100 – Das absolute Endschiff',       color: '#fbbf24', glowColor: '#f59e0b', emoji: '👑' },
];

// ── S2 Bonus Milestones — deflationiert ──
// Bewusst klein: jeder Bonus-Token ist jetzt ein echter "Moment"
export const LEVEL_UP_BONUS_S2 = {
  10:  { tokens: 250,   label: '🎁 Level-10-Meilenstein' },
  20:  { tokens: 400,   label: '🎁 Level-20-Meilenstein' },
  30:  { tokens: 600,   label: '🎁 Level-30-Meilenstein' },
  40:  { tokens: 800,   label: '🎁 Level-40-Meilenstein' },
  50:  { tokens: 1200,  label: '🏆 Halbzeit-Bonus!' },
  60:  { tokens: 1000,  label: '🎁 Level-60-Meilenstein' },
  70:  { tokens: 1200,  label: '🎁 Level-70-Meilenstein' },
  80:  { tokens: 1500,  label: '🎁 Level-80-Meilenstein' },
  90:  { tokens: 1800,  label: '🎁 Level-90-Meilenstein' },
  100: { tokens: 2500,  label: '👑 NEON APOCALYPSE ABGESCHLOSSEN!' },
};

const T = (amount, customRarity = null) => {
  let rarity = 'rare';
  let icon = '💰';
  if (amount >= 5000) { rarity = 'unique'; icon = '💎'; }
  else if (amount >= 2000) { rarity = 'legendary'; icon = '👑'; }
  else if (amount >= 1000) { rarity = 'epic'; icon = '🪙'; }
  
  if (customRarity) rarity = customRarity;
  
  return { type: 'tokens', amount, label: `${amount.toLocaleString('de-DE')} Tokens`, icon, rarity };
};

// ── FULL 100 LEVEL REWARD TRACK ──
export const SEASON_2_REWARDS = [

  // ── TIER 1: Überleben (1–10) ──
  { level: 1,
    free:    { type: 'badge',          id: 'bp_s2_survivor',      label: 'Badge: Survivor',            icon: '🛡️', rarity: 'rare' },
    premium: { type: 'title',          id: 'S2 Ankömmling',       label: 'Titel: S2 Ankömmling',       icon: '🏷️', rarity: 'epic' } },
  { level: 2,
    free:    T(250),
    premium: { type: 'chat_color',     id: 's2_blood_red',        label: 'Chat-Farbe: Blutrot',        icon: '💬', rarity: 'rare' } },
  { level: 3,
    free:    { type: 'badge',          id: 'bp_s2_scar',          label: 'Badge: Kampfnarbe',          icon: '⚔️', rarity: 'rare' },
    premium: { type: 'shard', tier: 'spark', label: 'Spark Shard', icon: '🔵', rarity: 'rare' } },
  { level: 4,
    free:    T(300),
    premium: { type: 'profile_effect', id: 's2_smoke',            label: 'Profil-Effekt: Rauchschwaden', icon: '💨', rarity: 'epic' } },
  { level: 5,
    free:    { type: 'theme',          id: 'crimson',             label: 'Theme: Crimson Red',         icon: '🎨', rarity: 'rare' },
    premium: { type: 'spaceship',      id: 's2_phantom',          label: 'Schiff: Phantom Strike',     icon: '👤', rarity: 'epic' } },
  { level: 6,
    free:    T(400),
    premium: T(800) },
  { level: 7,
    free:    { type: 'shard', tier: 'spark', label: 'Spark Shard', icon: '🔵', rarity: 'rare' },
    premium: { type: 'title',          id: 'Wasteland Warrior',   label: 'Titel: Wasteland Warrior',   icon: '🏷️', rarity: 'epic' } },
  { level: 8,
    free:    T(500),
    premium: { type: 'cursor_trail',   id: 's2_fire_trail',       label: 'Cursor: Feuerspur',          icon: '🔥', rarity: 'epic' } },
  { level: 9,
    free:    T(600),
    premium: T(1000) },
  { level: 10,
    free:    { type: 'frame',          id: 's2_apocalypse',       label: 'Rahmen: Apocalypse',         icon: '🖼️', rarity: 'epic' },
    premium: { type: 'bg_animation',   id: 'apocalypse_meteors',  label: 'Hintergrund: Meteorregen',   icon: '☄️', rarity: 'legendary' } },

  // ── TIER 2: Radioaktiv (11–20) ──
  { level: 11,
    free:    T(700),
    premium: { type: 'chat_color',     id: 's2_toxic_green',      label: 'Chat-Farbe: Toxic Green',    icon: '💬', rarity: 'epic' } },
  { level: 12,
    free:    { type: 'badge',          id: 'bp_s2_mutant',        label: 'Badge: Mutant',              icon: '🧟', rarity: 'epic' },
    premium: { type: 'shard', tier: 'spark', label: 'Spark Shard', icon: '🔵', rarity: 'rare' } },
  { level: 13,
    free:    T(800),
    premium: { type: 'profile_effect', id: 's2_radiation',        label: 'Profil-Effekt: Strahlung',   icon: '☢️', rarity: 'epic' } },
  { level: 14,
    free:    { type: 'theme',          id: 'volcanic',            label: 'Theme: Vulkan',              icon: '🌋', rarity: 'epic' },
    premium: T(1200) },
  { level: 15,
    free:    T(900),
    premium: { type: 'bg_animation',   id: 'crimson_storm',       label: 'Hintergrund: Crimson Storm', icon: '⚡', rarity: 'legendary' } },
  { level: 16,
    free:    { type: 'badge',          id: 'bp_s2_infected',      label: 'Badge: Infiziert',           icon: '🦠', rarity: 'epic' },
    premium: { type: 'title',          id: 'Contaminated',        label: 'Titel: The Contaminated',    icon: '🏷️', rarity: 'epic' } },
  { level: 17,
    free:    T(1000),
    premium: { type: 'shard', tier: 'void', label: 'Void Shard', icon: '🟣', rarity: 'epic' } },
  { level: 18,
    free:    { type: 'chat_color',     id: 's2_biohazard',        label: 'Chat-Farbe: Biohazard',      icon: '💬', rarity: 'epic' },
    premium: { type: 'cursor_trail',   id: 's2_toxic_trail',      label: 'Cursor: Toxic Drop',         icon: '☣️', rarity: 'legendary' } },
  { level: 19,
    free:    T(1200),
    premium: T(1800) },
  { level: 20,
    free:    { type: 'frame',          id: 's2_mutant',           label: 'Rahmen: Mutant',             icon: '🦠', rarity: 'legendary' },
    premium: { type: 'profile_effect', id: 's2_biohazard_aura',   label: 'Profil-Effekt: Biohazard Aura', icon: '☢️', rarity: 'legendary' } },

  // ── TIER 3: Wasteland (21–30) ──
  { level: 21,
    free:    T(1400),
    premium: { type: 'title',          id: 'Apocalypse Survivor', label: 'Titel: Apocalypse Survivor', icon: '🏷️', rarity: 'epic' } },
  { level: 22,
    free:    { type: 'badge',          id: 'bp_s2_scavenger',     label: 'Badge: Plünderer',           icon: '🔍', rarity: 'epic' },
    premium: { type: 'shard', tier: 'spark', label: '2x Spark Shard', icon: '🔵🔵', rarity: 'rare' } },
  { level: 23,
    free:    T(1600),
    premium: { type: 'profile_effect', id: 's2_dust_storm',       label: 'Profil-Effekt: Staubsturm',  icon: '🌪️', rarity: 'epic' } },
  { level: 24,
    free:    { type: 'theme',          id: 'stealth',             label: 'Theme: Stealth',             icon: '🎨', rarity: 'epic' },
    premium: T(2200) },
  { level: 25,
    free:    T(1800),
    premium: { type: 'bg_animation',   id: 'neon_rain',           label: 'Hintergrund: Neon-Regen',    icon: '💻', rarity: 'legendary' } },
  { level: 26,
    free:    { type: 'badge',          id: 'bp_s2_warlord',       label: 'Badge: Kriegsherr',          icon: '⚔️', rarity: 'epic' },
    premium: { type: 'chat_color',     id: 's2_apocalypse_orange', label: 'Chat-Farbe: Apocalypse',    icon: '💬', rarity: 'legendary' } },
  { level: 27,
    free:    T(2000),
    premium: { type: 'shard', tier: 'void', label: 'Void Shard', icon: '🟣', rarity: 'epic' } },
  { level: 28,
    free:    { type: 'cursor_trail',   id: 's2_lightning_bolt',   label: 'Cursor: Blitzeinschlag',     icon: '⚡', rarity: 'epic' },
    premium: { type: 'title',          id: 'Vault Breaker',       label: 'Titel: Vault Breaker',       icon: '🏷️', rarity: 'legendary' } },
  { level: 29,
    free:    T(2200),
    premium: T(2800) },
  { level: 30,
    free:    { type: 'frame',          id: 'blood',               label: 'Rahmen: Blood Moon',         icon: '🩸', rarity: 'legendary' },
    premium: { type: 'cursor_trail',   id: 's2_wasteland_comet',  label: 'Cursor: Wasteland Comet',    icon: '☄️', rarity: 'legendary' } },

  // ── TIER 4: Void Rising (31–40) ──
  { level: 31,
    free:    T(2400),
    premium: { type: 'bg_animation',   id: 'void_pulse',          label: 'Hintergrund: Void Pulse',    icon: '🌀', rarity: 'legendary' } },
  { level: 32,
    free:    { type: 'badge',          id: 'bp_s2_void_touched',  label: 'Badge: Void Touched',        icon: '🕳️', rarity: 'legendary' },
    premium: { type: 'shard', tier: 'void', label: 'Void Shard', icon: '🟣', rarity: 'epic' } },
  { level: 33,
    free:    T(2600),
    premium: { type: 'profile_effect', id: 's2_void_aura',        label: 'Profil-Effekt: Void Aura',   icon: '🌀', rarity: 'legendary' } },
  { level: 34,
    free:    { type: 'theme',          id: 'midnight',            label: 'Theme: Midnight',            icon: '🌙', rarity: 'epic' },
    premium: T(3200) },
  { level: 35,
    free:    T(2800),
    premium: { type: 'title',          id: 'Void Walker',         label: 'Titel: Void Walker',         icon: '🏷️', rarity: 'legendary' } },
  { level: 36,
    free:    { type: 'chat_color',     id: 's2_void_purple',      label: 'Chat-Farbe: Void Purple',    icon: '💬', rarity: 'legendary' },
    premium: { type: 'cursor_trail',   id: 's2_void_trail',       label: 'Cursor: Void Rift',          icon: '🌀', rarity: 'legendary' } },
  { level: 37,
    free:    T(3000),
    premium: { type: 'shard', tier: 'void', label: '2x Void Shard', icon: '🟣🟣', rarity: 'epic' } },
  { level: 38,
    free:    { type: 'badge',          id: 'bp_s2_rift_lord',     label: 'Badge: Rift Lord',           icon: '🔮', rarity: 'legendary' },
    premium: { type: 'profile_effect', id: 's2_dark_matter',      label: 'Profil-Effekt: Dark Matter', icon: '🌑', rarity: 'legendary' } },
  { level: 39,
    free:    T(3200),
    premium: T(4000) },
  { level: 40,
    free:    { type: 'frame',          id: 'void',                label: 'Rahmen: Void',               icon: '🌑', rarity: 'legendary' },
    premium: { type: 'spaceship',      id: 's2_hellfire',         label: 'Schiff: Hellfire Mk.II',     icon: '🔥', rarity: 'legendary' } },

  // ── TIER 5: Neon God (41–50) ──
  { level: 41,
    free:    T(3400),
    premium: { type: 'chat_color',     id: 's2_neon_god_cyan',    label: 'Chat-Farbe: Neon God Cyan',  icon: '💬', rarity: 'legendary' } },
  { level: 42,
    free:    { type: 'badge',          id: 'bp_s2_neon_god',      label: 'Badge: Neon God',            icon: '🌟', rarity: 'legendary' },
    premium: { type: 'shard', tier: 'nova', label: 'Nova Shard', icon: '🟡', rarity: 'legendary' } },
  { level: 43,
    free:    T(3600),
    premium: { type: 'profile_effect', id: 's2_electric_halo',    label: 'Profil-Effekt: Electric Halo', icon: '💫', rarity: 'legendary' } },
  { level: 44,
    free:    { type: 'theme',          id: 'dark_neon',           label: 'Theme: Dark Neon',           icon: '🎨', rarity: 'legendary' },
    premium: T(4500) },
  { level: 45,
    free:    T(3800),
    premium: { type: 'title',          id: 'Electric Deity',      label: 'Titel: Electric Deity',      icon: '🏷️', rarity: 'unique' } },
  { level: 46,
    free:    { type: 'cursor_trail',   id: 's2_electric_trail',   label: 'Cursor: Elektro-Blitz',      icon: '⚡', rarity: 'legendary' },
    premium: T(5000) },
  { level: 47,
    free:    { type: 'shard', tier: 'nova', label: 'Nova Shard', icon: '🟡', rarity: 'legendary' },
    premium: { type: 'bg_animation',   id: 'aurora_north',        label: 'Hintergrund: Aurora Borealis', icon: '🌌', rarity: 'unique' } },
  { level: 48,
    free:    { type: 'badge',          id: 'bp_s2_thunder_god',   label: 'Badge: Donnergott',          icon: '⚡', rarity: 'legendary' },
    premium: { type: 'profile_effect', id: 's2_thunder_crown',    label: 'Profil-Effekt: Donner-Krone', icon: '👑', rarity: 'unique' } },
  { level: 49,
    free:    T(4200),
    premium: T(5500) },
  { level: 50,
    free:    { type: 'frame',          id: 's2_doomsday',         label: 'Rahmen: Doomsday',           icon: '☄️', rarity: 'unique' },
    premium: { type: 'title',          id: 'Neon God',            label: 'Titel: Neon God',            icon: '🏷️', rarity: 'unique' } },

  // ── TIER 6: Cosmic Warlord (51–60) ──
  { level: 51,
    free:    T(4500),
    premium: { type: 'title',          id: 'Cosmic Warlord',      label: 'Titel: Cosmic Warlord',      icon: '🏷️', rarity: 'unique' } },
  { level: 52,
    free:    { type: 'badge',          id: 'bp_s2_galaxy_lord',   label: 'Badge: Galaxy Lord',         icon: '🌌', rarity: 'unique' },
    premium: T(6000) },
  { level: 53,
    free:    { type: 'shard', tier: 'nova', label: 'Nova Shard', icon: '🟡', rarity: 'legendary' },
    premium: { type: 'chat_color',     id: 's2_supernova',        label: 'Chat-Farbe: Supernova',      icon: '💬', rarity: 'unique' } },
  { level: 54,
    free:    { type: 'theme',          id: 'galaxy',              label: 'Theme: Galaxy',              icon: '🌠', rarity: 'unique' },
    premium: T(6500) },
  { level: 55,
    free:    T(4800),
    premium: { type: 'profile_effect', id: 's2_galaxy_storm',     label: 'Profil-Effekt: Galaxy Storm', icon: '🌠', rarity: 'unique' } },
  { level: 56,
    free:    { type: 'cursor_trail',   id: 's2_stardust',         label: 'Cursor: Sternenstaub',       icon: '✨', rarity: 'unique' },
    premium: T(7000) },
  { level: 57,
    free:    { type: 'shard', tier: 'nova', label: 'Nova Shard', icon: '🟡', rarity: 'legendary' },
    premium: { type: 'title',          id: 'Galactic Destroyer',  label: 'Titel: Galactic Destroyer',  icon: '🏷️', rarity: 'unique' } },
  { level: 58,
    free:    { type: 'badge',          id: 'bp_s2_nebula_god',    label: 'Badge: Nebula God',          icon: '💫', rarity: 'unique' },
    premium: { type: 'bg_animation',   id: 'galaxy_spiral',       label: 'Hintergrund: Galaxie Spirale', icon: '🌠', rarity: 'unique' } },
  { level: 59,
    free:    T(5200),
    premium: T(8000) },
  { level: 60,
    free:    { type: 'frame',          id: 'legendary',           label: 'Rahmen: Legendary',          icon: '🔱', rarity: 'unique' },
    premium: { type: 'spaceship',      id: 's2_ghost',            label: 'Schiff: Ghost Protocol',     icon: '👻', rarity: 'unique' } },

  // ── TIER 7: Transcended (61–70) ──
  { level: 61,
    free:    T(5500),
    premium: { type: 'profile_effect', id: 's2_transcend_aura',   label: 'Profil-Effekt: Transcend Aura', icon: '✨', rarity: 'unique' } },
  { level: 62,
    free:    { type: 'badge',          id: 'bp_s2_transcendent',  label: 'Badge: Transcendent',        icon: '🔮', rarity: 'unique' },
    premium: { type: 'shard', tier: 'nova', label: '2x Nova Shard', icon: '🟡🟡', rarity: 'legendary' } },
  { level: 63,
    free:    T(5800),
    premium: { type: 'chat_color',     id: 's2_divine_pink',      label: 'Chat-Farbe: Divine Pink',    icon: '💬', rarity: 'unique' } },
  { level: 64,
    free:    { type: 'theme',          id: 'hub_2_0',             label: 'Theme: 7B Hub 2.0',          icon: '🎨', rarity: 'unique' },
    premium: T(9000) },
  { level: 65,
    free:    T(6200),
    premium: { type: 'title',          id: 'The Transcended',     label: 'Titel: The Transcended',     icon: '🏷️', rarity: 'unique' } },
  { level: 66,
    free:    { type: 'cursor_trail',   id: 's2_divine_trail',     label: 'Cursor: Göttliches Licht',   icon: '🌟', rarity: 'unique' },
    premium: { type: 'profile_effect', id: 's2_holy_wings',       label: 'Profil-Effekt: Heilige Schwingen', icon: '🪽', rarity: 'unique' } },
  { level: 67,
    free:    T(6500),
    premium: { type: 'shard', tier: 'omega', label: 'Omega Shard', icon: '🔴', rarity: 'unique' } },
  { level: 68,
    free:    { type: 'badge',          id: 'bp_s2_dimension_lord', label: 'Badge: Dimension Lord',     icon: '🌀', rarity: 'unique' },
    premium: { type: 'title',          id: 'Dimension Breaker',   label: 'Titel: Dimension Breaker',   icon: '🏷️', rarity: 'unique' } },
  { level: 69,
    free:    T(7000),
    premium: T(10000) },
  { level: 70,
    free:    { type: 'frame',          id: 'divine',              label: 'Rahmen: Divine',             icon: '🌟', rarity: 'unique' },
    premium: { type: 'title',          id: 'Doom Bringer',        label: 'Titel: Doom Bringer',        icon: '🏷️', rarity: 'unique' } },

  // ── TIER 8: Apex (71–80) ──
  { level: 71,
    free:    T(7500),
    premium: { type: 'chat_color',     id: 's2_apex_gold',        label: 'Chat-Farbe: Apex Gold',      icon: '💬', rarity: 'unique' } },
  { level: 72,
    free:    { type: 'badge',          id: 'bp_s2_apex',          label: 'Badge: Apex',                icon: '👑', rarity: 'unique' },
    premium: { type: 'shard', tier: 'omega', label: 'Omega Shard', icon: '🔴', rarity: 'unique' } },
  { level: 73,
    free:    T(8000),
    premium: { type: 'profile_effect', id: 's2_apex_flare',       label: 'Profil-Effekt: Apex Flare',  icon: '🔥', rarity: 'unique' } },
  { level: 74,
    free:    { type: 'theme',          id: 'gold',                label: 'Theme: Gold',                icon: '🥇', rarity: 'unique' },
    premium: T(12000) },
  { level: 75,
    free:    T(8500),
    premium: { type: 'title',          id: 'Apex Predator',       label: 'Titel: Apex Predator',       icon: '🏷️', rarity: 'unique' } },
  { level: 76,
    free:    { type: 'cursor_trail',   id: 's2_apex_comet',       label: 'Cursor: Apex Komet',         icon: '💫', rarity: 'unique' },
    premium: T(13500) },
  { level: 77,
    free:    { type: 'shard', tier: 'nova', label: 'Nova Shard', icon: '🟡', rarity: 'legendary' },
    premium: { type: 'profile_effect', id: 's2_golden_wings',     label: 'Profil-Effekt: Goldene Schwingen', icon: '🪽', rarity: 'unique' } },
  { level: 78,
    free:    { type: 'badge',          id: 'bp_s2_gold_god',      label: 'Badge: Gold God',            icon: '🥇', rarity: 'unique' },
    premium: T(15000) },
  { level: 79,
    free:    T(9000),
    premium: { type: 'chat_color',     id: 's2_omega_white',      label: 'Chat-Farbe: Omega White',    icon: '💬', rarity: 'unique' } },
  { level: 80,
    free:    { type: 'frame',          id: 'galaxy',              label: 'Rahmen: Galaxy',             icon: '🌌', rarity: 'unique' },
    premium: { type: 'spaceship',      id: 's2_titan',            label: 'Schiff: Apocalypse Titan',   icon: '🌌', rarity: 'unique' } },

  // ── TIER 9: Eternal (81–90) ──
  { level: 81,
    free:    T(10000),
    premium: { type: 'title',          id: 'The Eternal',         label: 'Titel: The Eternal',         icon: '🏷️', rarity: 'unique' } },
  { level: 82,
    free:    { type: 'badge',          id: 'bp_s2_eternal',       label: 'Badge: Eternal',             icon: '♾️', rarity: 'unique' },
    premium: { type: 'shard', tier: 'omega', label: 'Omega Shard', icon: '🔴', rarity: 'unique' } },
  { level: 83,
    free:    T(11000),
    premium: { type: 'profile_effect', id: 's2_eternal_glow',     label: 'Profil-Effekt: Eternal Glow', icon: '♾️', rarity: 'unique' } },
  { level: 84,
    free:    { type: 'theme',          id: 'cyber',               label: 'Theme: Cyber',               icon: '🔵', rarity: 'unique' },
    premium: T(18000) },
  { level: 85,
    free:    T(12000),
    premium: { type: 'cursor_trail',   id: 's2_eternal_trail',    label: 'Cursor: Eternal Flame',      icon: '♾️', rarity: 'unique' } },
  { level: 86,
    free:    { type: 'shard', tier: 'omega', label: 'Omega Shard', icon: '🔴', rarity: 'unique' },
    premium: T(20000) },
  { level: 87,
    free:    T(13000),
    premium: { type: 'profile_effect', id: 's2_supernova_burst',  label: 'Profil-Effekt: Supernova Burst', icon: '🌟', rarity: 'unique' } },
  { level: 88,
    free:    { type: 'badge',          id: 'bp_s2_void_emperor',  label: 'Badge: Void Emperor',        icon: '🌑', rarity: 'unique' },
    premium: T(22000) },
  { level: 89,
    free:    T(14000),
    premium: { type: 'title',          id: 'Emperor of the Void', label: 'Titel: Emperor of the Void', icon: '🏷️', rarity: 'unique' } },
  { level: 90,
    free:    { type: 'frame',          id: 'eternal',             label: 'Rahmen: Eternal',            icon: '♾️', rarity: 'unique' },
    premium: { type: 'cursor_trail',   id: 's2_omega_trail',      label: 'Cursor: Omega Blaze',        icon: '🌌', rarity: 'unique' } },

  // ── TIER 10: NEON APOCALYPSE (91–100) ──
  { level: 91,
    free:    T(16000),
    premium: { type: 'chat_color',     id: 's2_final_red',        label: 'Chat-Farbe: Final Red',      icon: '💬', rarity: 'unique' } },
  { level: 92,
    free:    { type: 'badge',          id: 'bp_s2_apocalypse',    label: 'Badge: Apocalypse',          icon: '☄️', rarity: 'unique' },
    premium: T(25000) },
  { level: 93,
    free:    { type: 'shard', tier: 'omega', label: 'Omega Shard', icon: '🔴', rarity: 'unique' },
    premium: { type: 'profile_effect', id: 's2_apocalypse_aura',  label: 'Profil-Effekt: Apocalypse Aura', icon: '💥', rarity: 'unique' } },
  { level: 94,
    free:    { type: 'cursor_trail',   id: 's2_apocalypse_comet', label: 'Cursor: Apokalypse-Komet',   icon: '☄️', rarity: 'unique' },
    premium: T(30000) },
  { level: 95,
    free:    T(18000),
    premium: { type: 'title',          id: 'Neon Apocalypse',     label: 'Titel: Neon Apocalypse',     icon: '🏷️', rarity: 'unique' } },
  { level: 96,
    free:    { type: 'badge',          id: 'bp_s2_end_times',     label: 'Badge: End Times',           icon: '👁️', rarity: 'unique' },
    premium: T(35000) },
  { level: 97,
    free:    { type: 'shard', tier: 'omega', label: '2x Omega Shard', icon: '🔴🔴', rarity: 'unique' },
    premium: { type: 'profile_effect', id: 's2_omega_aura',       label: 'Profil-Effekt: Omega Aura',  icon: '🌌', rarity: 'unique' } },
  { level: 98,
    free:    { type: 'frame',          id: 'void_titan',          label: 'Rahmen: Void Titan',         icon: '🌑', rarity: 'unique' },
    premium: T(45000) },
  { level: 99,
    free:    { type: 'shard', tier: 'omega', label: '3x Omega Shard', icon: '🔴🔴🔴', rarity: 'unique' },
    premium: { type: 'title',          id: 'Omega Being',         label: 'Titel: Omega Being',         icon: '🏷️', rarity: 'unique' } },
  { level: 100,
    free:    T(25000),
    premium: { type: 'spaceship',      id: 's2_apex',             label: 'Schiff: APEX Predator 👑',   icon: '👑', rarity: 'unique' } },
];

// ── Void Rift Key Milestones ──
// At these levels, players automatically receive a Void Rift Key
export const VOID_RIFT_KEY_LEVELS = [25, 50, 75, 100];

// ── Pro Pass Abilities (gameplay effects for Pro Pass holders) ──
export const PRO_PASS_ABILITIES = [
  {
    id: 'temporal_rewind',
    name: 'Temporaler Rückspuler',
    desc: 'Macht einen Fehler pro Spiel rückgängig. Das Schiff kehrt 2 Sekunden zurück.',
    icon: '⏪',
    color: '#06b6d4',
    keybind: '[R] / Button',
    cooldown: 'Einmalig pro Spiel',
    tier: 'pro_pass',
  },
  {
    id: 'notfall_warp',
    name: 'Notfall-Warp',
    desc: 'Teleportiert dich sofort in die Bildschirmmitte und gibt 2s Unverwundbarkeit.',
    icon: '🌐',
    color: '#a855f7',
    keybind: '[E] / Button',
    cooldown: '45s Cooldown',
    tier: 'pro_pass',
  },
  {
    id: 'score_overdrive',
    name: 'Score Overdrive',
    desc: 'Aktiviere für 10s x3 Punkte-Multiplikator. Perfekt für Highscore-Runs.',
    icon: '🔥',
    color: '#f59e0b',
    keybind: '[Q] / Button',
    cooldown: '60s Cooldown',
    tier: 'pro_pass',
  },
];

export const BATTLE_PASS_SEASON_2 = {
  id: 'season_2',
  name: SEASON_2_NAME,
  description: SEASON_2_DESCRIPTION,
  premiumPrice: SEASON_2_PREMIUM_PRICE,
  maxLevel: 100,
  xpPerLevel: 1500,
  rewards: SEASON_2_REWARDS,
};